version: 2

jobs:
  docs-build:
    docker:
      - image: cimg/python:3.10  # o 3.11
    steps:
      - checkout
      - run:
          name: Installa LaTeX
          command: |
            sudo apt-get update
            sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-lang-italian latexmk make ghostscript tex-gyre git
      - run:
          name: Compile SPHINX
          command: |
            pip install -r requirements.txt
            make html
            make epub
            make latexpdf
            cp _build/epub/*.epub _build/html/
            cp _build/latex/*.pdf _build/html/
            touch _build/html/.nojekyll
      - persist_to_workspace:
          root: _build
          paths:
            - html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:1WBi2toG3UT3dRHQIKB9ur78gBMBinG+3Bh54cwlA/g"
      - checkout
      - attach_workspace:
          at: _build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "cristian.lucchesi@iit.cnr.it"
            git config user.name "cristian.lucchesi"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist _build/html
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docs-build:
          filters:
            branches:
              only: main
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: main