--- 
document:
  name: "Piattaforma TransparenzAI"
  description: "Piattaforma per l'analisi e la consultazione della trasparenza amministrativa delle Pubbliche Amministrazioni"
  github_user: trasparenzai
  github_repo: trasparenzai.github.io
  github_version: master/docs
  downloads:
    - type: pdf
      url: ../manuale-trasparenzai.pdf
